### ISSUE TITLE
랜딩 페이지 마크업

### ISSUE THREAD

**Issue by hyungwookchoi** [Blockchain-Lighthouse/SmartMatch_FE#2]
## 예상 동작
- 랜딩 페이지 마크업

### Tasks
- [x] 랜딩 페이지 구조 설계
- [x] 페이지 마크업
  - [x] Header Mark-up
  - [x] MainBlock Mark-up
- [x] FullScreen Scroll 동작

**Comment by ctdlog** [comment]
https://github.com/Blockchain-Lighthouse/SmartAuction_FE/commit/52b3ab4cf2a7b311e6a4717fdae2a0efa6a06e1d

**Comment by ctdlog** [comment]
https://github.com/Blockchain-Lighthouse/SmartAuction_FE/commit/fe344a0a6a46803867fa4e9e9a0e1199a7ea9b64

full-page scroll 구현.

**Comment by ctdlog** [comment]
https://github.com/Blockchain-Lighthouse/SmartAuction_FE/commit/fdbbc8026d7ff687af9a6ad252503c0f1afd328c

2페이지를 Description 페이지로 개발 중입니다.
